using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Store.Ui;

[GenerateTypedNameReferences]
public sealed partial class StoreListingControl : Control
{
    public StoreListingControl(string itemName, string itemDescription,
        string price, string oldPrice, bool canBuy, Texture? texture = null)
    {
        RobustXamlLoader.Load(this);

        StoreItemName.Text = itemName;
        StoreItemDescription.SetMessage(itemDescription);

        StoreItemPriceWithoutDiscount.Text = oldPrice;
        StoreItemPriceWithoutDiscount.Visible = price != oldPrice;

        StoreItemBuyButton.Text = price;
        StoreItemBuyButton.Disabled = !canBuy;

        StoreItemTexture.Texture = texture;
    }
}
